version: '3'
services:
  kafka:
    image: spotify/kafka:latest
    ports:
    - "9092:9092"
    - "2181:2181"
    hostname: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      AUTO_CREATE_TOPICS: "true"
    command: >
      bash -c
      "(sleep 15s &&
      /opt/kafka_2.11-0.10.1.0/bin/kafka-topics.sh
      --create
      --zookeeper localhost:2181 
      --replication-factor 1 
      --partitions 1
      --topic csv_topic &) && (supervisord -n)"

  csvtokafka:
    restart: always
    build: producer/.
    working_dir: /app
    ports:
    - "8080:8080"
    depends_on:
      - kafka

  consumer1:
    restart: always
    build: consumer1/.
    working_dir: /app
    ports:
    - "80:80"
    depends_on:
      - kafka
      - csvtokafka
   
  consumer2:
    restart: always
    build: consumer2/.
    working_dir: /app
    ports:
        - "81:81"
    depends_on:
        - kafka
        - csvtokafka

  consumer3:
    restart: always
    build: consumer3/.
    working_dir: /app
    ports:
      - "8083:83"
    depends_on:
      - kafka
      - csvtokafka